require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6.9
  Exclude:
    - 'app/models/**/*'
    - 'spec/**/*'
    - 'db/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Rails/FilePath:
  Enabled: false

Layout/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 30
